services:
  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
    volumes:
      - ~/data:/var/lib/postgres/data

volumes:
  data:
